# Generated by Django 2.1.4 on 2019-01-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pic',
            field=models.ImageField(default='/static/games/image_placeholder.jpg', upload_to='account/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='member',
            name='proffession',
            field=models.TextField(default='Works at gameworkshop'),
        ),
    ]
