# Generated by Django 2.1.4 on 2019-01-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190119_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.ImageField(default='/media/account/image_placeholder.jpg', upload_to='account'),
        ),
    ]
