# Generated by Django 2.1.4 on 2019-01-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190121_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='account'),
        ),
        migrations.AlterField(
            model_name='member',
            name='proffession',
            field=models.TextField(blank=True, null=True),
        ),
    ]
