# Generated by Django 2.1.4 on 2019-01-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190121_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pic',
            field=models.ImageField(default='/media/account/image_placeholder.jpg', upload_to='account/%Y/%m/%d'),
        ),
    ]
