# Generated by Django 2.1.4 on 2019-01-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190121_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='proffession',
            field=models.TextField(blank=True, default='works at gameworkshop', null=True),
        ),
    ]
