language: python 
python:
  - "3.6"
  - "nightly"

env: 
  - DJANGO=2.1.4 DB=postgres

# command to install dependecies
install:
  - "pip install pytest"
  - "pip install -r requirements.txt"

# command to run test
script:   python manage.py test