language: python 
python:
  - "3.6"
  - "nightly"

env: 
  - DJANGO=2.1.4 DB=postgres

addons:
  postgresql: "10"

# command to install dependecies
install:
  - "pip install -r requirements.txt"
#
# command to run test
script:   python manage.py test