# Generated by Django 2.1.4 on 2019-01-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='topic',
            field=models.CharField(default='no topic', max_length=2500),
            preserve_default=False,
        ),
    ]
