# Generated by Django 2.1.4 on 2019-01-17 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('views', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='blogs/%Y/%m/%d')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(upload_to='blogs/%Y/%m/%d')),
                ('image_two', models.ImageField(upload_to='blogs/%Y/%m/%d')),
                ('image_three', models.ImageField(upload_to='blogs/%Y/%m/%d')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='blog.Blog')),
            ],
        ),
    ]
