# Generated by Django 2.1.4 on 2019-01-01 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamelist', '0002_gamelist_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('game_developer', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('image_cover', models.ImageField(upload_to='')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
                ('views', models.IntegerField(default=0)),
                ('game_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='gamelist.GameList')),
            ],
        ),
    ]
