# Generated by Django 2.1.4 on 2019-01-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamelist', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='gamelist.GameList'),
        ),
    ]
