# Generated by Django 2.1.4 on 2019-01-01 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
        migrations.AlterField(
            model_name='game',
            name='image_cover',
            field=models.ImageField(upload_to='games'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='game.Game'),
        ),
    ]
