# Generated by Django 2.1.4 on 2019-01-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190109_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image_cover',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
