# Generated by Django 2.1.4 on 2019-01-01 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelist',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2019, 1, 1, 19, 4, 38, 587733, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
