# Generated by Django 2.1.4 on 2019-01-01 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0003_remove_gamelist_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelist',
            old_name='title',
            new_name='name',
        ),
    ]
