# Generated by Django 2.1.4 on 2019-01-01 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0005_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamelist.Member'),
        ),
    ]
