# Generated by Django 2.1.4 on 2019-01-09 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelist', '0007_auto_20190102_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelist',
            name='views',
        ),
    ]
